### ISSUE TITLE
Changes not saved

### ISSUE THREAD

**Issue by quees** [Codiad/Codiad#841] opened 2015-07-01 11:45 UTC
Hi, I was using last version, 2.6.5 and was having the impression some changes where no saved. Now i have a file that is allways not saved. File is 247 lines of code. You could acces the file at http://eonli.com/codiad/tst.htm .

Every time I move line 228 to 229 position and line 229 to 228 position, respecting everything else, tabs included and Save the file, says "File saved", then I close and reopen the file, the change is not saved.

I have tested with version 2.6.5 in two different servers from different host companies and get the same error. Have tested with master version and get same error and tried too at Codiad demo page, http://http://demo.codiad.com   where I created a new file and pasted the content, saved, edited, saved and get the same problem.

**Comment by quees** [comment] 2015-07-03 10:39
After some further tests I believe there are consistency problems between diff_match_patch.js and noxodin diff_match_patch.php. The diff/patch I get with diff_match_patch.js when I commute line 228 & 229, is not applied by diff_match_patch.php and any error/warning is throw (It works perfect with other patches).

(Then file in local and in server are not equal. In 3 or 4 ocassions I continued editing and finished with a 'corrupted-style' or empty file I must recover from backup).

As a temporal solution I edited line 490 in \components\active\init.js changing
                        codiad.filemanager.savePatch(path, patch, session.serverMTime, {
with
                        codiad.filemanager.saveFile(path, newContent, {

then the diff/patch is not used but the full content uploaded.

Perhaps sendind a crc from local file/string with the diff/patch to compare with server file/string after patch is applied and if dont match then full content uploaded....

**Comment by joeinnes** [comment] 2015-09-15 19:23
I'm having the issue too. The work-around above seems to fix the issue, but it prompts me every time saying the server has a more recent version of the file.

**Comment by joeinnes** [comment] 2015-09-15 20:08
It looks like this is a duplicate of #828 - the problem seems to be that the diffing doesn't handle accented characters. I'm not good enough to actually fix this, but perhaps quees can confirm: are there any accented characters in what you're trying to save?

**Comment by quees** [comment] 2015-09-19 10:12
Yes, it have accented characters. The file link is at the first message, http://eonli.com/codiad/tst.htm and you can reproduce the error with the guidelines on it. 

I  have tested with your patch, [<b>Set encoding as UTF-8 in diff_match_patch.php</b> #862] (https://github.com/Codiad/Codiad/issues/862) and <b>now the file is correctly saved.</b>

I believe further tests are necessary, but right now, it works for me.

Many thanks joeinnes !!

**Comment by daeks** [comment] 2015-09-19 13:09
:+1:

**Closed** 2016-02-02 10:51 UTC
Labels: Bug
